AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket and IAM user with access to that bucket.

Resources:
  s3buckets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ekenepcloudformationbucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256


